In [1]:
import numpy as np

In [2]:
v1=np.array([[1, 2, 3],[4,5,6]])
v2=np.array([[7, 8, 9],[10,11,12]])

In [ ]:
np.percentile(v1,99)#99th precentile

np.float64(5.95)

In [4]:
v1+v2

array([[ 8, 10, 12],
       [14, 16, 18]])

In [6]:
v1.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [7]:
np.linalg.det([[1, 2], [3, 4]])

np.float64(-2.0000000000000004)

In [8]:
np.linalg.eig([[1, 2], [3, 4]])

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [9]:
a=np.array([[1,2],[3,5]])
a

array([[1, 2],
       [3, 5]])

In [10]:
np.linalg.inv(a)

array([[-5.,  2.],
       [ 3., -1.]])

In [11]:
np.linalg.eig(a)

EigResult(eigenvalues=array([-0.16227766,  6.16227766]), eigenvectors=array([[-0.86460354, -0.36126098],
       [ 0.50245469, -0.93246475]]))

In [12]:
np.linalg.solve(a,[[6,7],[8,9]])

array([[-14., -17.],
       [ 10.,  12.]])

In [13]:
np.linalg.svd(a)

SVDResult(U=array([[-0.35737275, -0.93396184],
       [-0.93396184,  0.35737275]]), S=array([6.24294338, 0.16018085]), Vh=array([[-0.50605269, -0.86250257],
       [ 0.86250257, -0.50605269]]))

# vector

In [14]:
v1=np.array([1, 2, 3])
v2=np.array([4, 5, 6])
print(v1+v2)
print(v1-v2)
print(v1*2)

[5 7 9]
[-3 -3 -3]
[2 4 6]


In [15]:
np.dot(v1, v2)

np.int64(32)

In [16]:
np.linalg.norm(v1)

np.float64(3.7416573867739413)