In [1]:
import numpy as np

In [2]:
v1=np.array([1, 2, 3])
v2=np.array([4, 5, 6])
print(v1+v2)
print(v1-v2)
print(v1*2)

[5 7 9]
[-3 -3 -3]
[2 4 6]


In [3]:
np.dot(v1, v2)

np.int64(32)

In [4]:
np.linalg.norm(v1)

np.float64(3.7416573867739413)