In [1]:
import pandas as pd
import numpy as np
import sklearn.svm as svc
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_digits

digits=load_digits()

In [2]:
from sklearn.ensemble import RandomForestClassifier
df=pd.DataFrame(digits.data)    

In [24]:
x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.3)

In [4]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

C:\Users\Jeevan kumar\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9518518518518518

In [5]:
rdm=RandomForestClassifier()
rdm.fit(x_train,y_train)
rdm.score(x_test,y_test)

0.9722222222222222

In [6]:
model=svc.SVC()
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.987037037037037

In [7]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=5)
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [8]:
for train_index,test_index in kf.split(df):
   print("TRAIN INDEX:",train_index,"TEST INDEX:",test_index)

TRAIN INDEX: [ 360  361  362 ... 1794 1795 1796] TEST INDEX: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 23

In [9]:
def get_score(model, x_train, x_test, y_train, y_test):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

In [10]:
get_score(LogisticRegression(),x_train,x_test,y_train,y_test)

C:\Users\Jeevan kumar\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9518518518518518

In [11]:
get_score(svc.SVC(),x_train,x_test,y_train,y_test)

0.987037037037037

In [12]:
get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test)

0.9777777777777777

In [14]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

In [28]:
from sklearn.model_selection import cross_val_score

In [35]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
cross_val_score(DecisionTreeClassifier(),digits.data,digits.target)

array([0.78611111, 0.70555556, 0.80779944, 0.8356546 , 0.80501393])

In [ ]:
cross_val_score(svc.SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [33]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

array([0.92222222, 0.89444444, 0.95543175, 0.95543175, 0.92479109])

<h1>pratices 

In [49]:
from sklearn.datasets import load_iris
iris=load_iris()

In [50]:
X = iris.data        # shape: (150, 4)
y = iris.target      # shape: (150,)


In [51]:
df=pd.DataFrame(X,columns=iris.feature_names)

In [52]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2


In [53]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [54]:
cross_val_score(svc.SVC(),df,y)

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [58]:
cross_val_score(RandomForestClassifier(n_estimators=40),df,y)

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [56]:
cross_val_score(DecisionTreeClassifier(),df,y)

array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ])