In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
rev_q1=np.array([10,12,9])
rev_q2=np.array([[8,11,7],[9,10,6]])

In [5]:
rev_q2[1,2]

np.int64(6)

In [6]:
rev_q2.reshape(3,2)

array([[ 8, 11],
       [ 7,  9],
       [10,  6]])

In [7]:
np.sort(rev_q1)

array([ 9, 10, 12])

In [4]:
q1=np.array([[200,220,250],[150,180,170],[300,280,260]])
q2=np.array([[210,230,240],[160,190,180],[310,290,270]])

In [5]:
q1+q2

array([[410, 450, 490],
       [310, 370, 350],
       [610, 570, 530]])

In [6]:
q2-q1

array([[ 10,  10, -10],
       [ 10,  10,  10],
       [ 10,  10,  10]])

In [7]:
(q2-q1)*100/q1

array([[ 5.        ,  4.54545455, -4.        ],
       [ 6.66666667,  5.55555556,  5.88235294],
       [ 3.33333333,  3.57142857,  3.84615385]])

In [9]:
price=np.array([[10,12,11],[8,9,10],[15,16,17]])
price

array([[10, 12, 11],
       [ 8,  9, 10],
       [15, 16, 17]])

In [13]:
q1_re=q1*price
q1_re

array([[2000, 2640, 2750],
       [1200, 1620, 1700],
       [4500, 4480, 4420]])

In [16]:
q1_re-(q1_re*.08)

array([[1840. , 2428.8, 2530. ],
       [1104. , 1490.4, 1564. ],
       [4140. , 4121.6, 4066.4]])

In [17]:
np.sum(q1_re-(q1_re*.08))

np.float64(23285.2)

In [18]:
features=np.array([[2000,3],[1800,2]])

In [19]:
weight=np.array([150,50000])

In [20]:
np.dot(features,weight)

array([450000, 370000])

In [21]:
price

array([[10, 12, 11],
       [ 8,  9, 10],
       [15, 16, 17]])

In [28]:
price[2,0]

np.int64(15)

In [29]:
price[1,1]

np.int64(9)

In [30]:
customer=np.array([[101,'mira'],[102,'sara'],[103,'john'],[104,'lisa']])
documaent=np.array([[101,250.50,'2024-06-01'],[102,300.75,'2024-06-02'],[103,150.25,'2024-06-03'],[104,400.00,'2024-06-04']])

In [34]:
t=np.hstack((customer,documaent))
t

array([['101', 'mira', '101', '250.5', '2024-06-01'],
       ['102', 'sara', '102', '300.75', '2024-06-02'],
       ['103', 'john', '103', '150.25', '2024-06-03'],
       ['104', 'lisa', '104', '400.0', '2024-06-04']], dtype='<U32')

In [ ]:
np.vstack((customer,documaent))

In [43]:
split,date=np.hsplit(t,[4])
split

array([['101', 'mira', '101', '250.5'],
       ['102', 'sara', '102', '300.75'],
       ['103', 'john', '103', '150.25'],
       ['104', 'lisa', '104', '400.0']], dtype='<U32')

In [44]:
date

array([['2024-06-01'],
       ['2024-06-02'],
       ['2024-06-03'],
       ['2024-06-04']], dtype='<U32')

In [45]:
np.vsplit(t,[4])

[array([['101', 'mira', '101', '250.5', '2024-06-01'],
        ['102', 'sara', '102', '300.75', '2024-06-02'],
        ['103', 'john', '103', '150.25', '2024-06-03'],
        ['104', 'lisa', '104', '400.0', '2024-06-04']], dtype='<U32'),
 array([], shape=(0, 5), dtype='<U32')]

In [47]:
monthly_sales=np.array([30,20,33,28,42])
result=monthly_sales<30
monthly_sales[result]

array([20, 28])

In [48]:
t

array([['101', 'mira', '101', '250.5', '2024-06-01'],
       ['102', 'sara', '102', '300.75', '2024-06-02'],
       ['103', 'john', '103', '150.25', '2024-06-03'],
       ['104', 'lisa', '104', '400.0', '2024-06-04']], dtype='<U32')

In [52]:
t[:,3]

array(['250.5', '300.75', '150.25', '400.0'], dtype='<U32')

In [55]:
tr=np.argmin(t[:,3])
tr

np.int64(2)

In [56]:
t[tr]

array(['103', 'john', '103', '150.25', '2024-06-03'], dtype='<U32')