In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets  import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection  import train_test_split

In [2]:
x,y=make_classification(
    n_features=10,
    n_samples=1000,
    n_informative=4,
    n_redundant=6,
    n_repeated=0,
    n_classes=2,
    weights=[0.9,0.1],
    random_state=42
)

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.25,random_state=42)

In [3]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report

# method 1: manually adjust parameter

In [4]:
model=DecisionTreeClassifier(criterion='entropy',max_depth=10)
model.fit(x_train,y_train)

y_pred=model.predict(x_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      0.96      0.95       221
           1       0.62      0.52      0.57        29

    accuracy                           0.91       250
   macro avg       0.78      0.74      0.76       250
weighted avg       0.90      0.91      0.90       250



# method 2: cross validation score

In [5]:
from sklearn.model_selection import cross_val_score

cross_val_score(DecisionTreeClassifier(criterion='gini',max_depth=5),x,y,cv=5)

array([0.945, 0.945, 0.94 , 0.975, 0.915])

In [6]:
cross_val_score(DecisionTreeClassifier(criterion='gini',max_depth=10),x,y,cv=5)

array([0.935, 0.94 , 0.95 , 0.95 , 0.915])

In [7]:
cross_val_score(DecisionTreeClassifier(criterion='entropy',max_depth=5),x,y,cv=5)

array([0.945, 0.89 , 0.94 , 0.95 , 0.915])

# method 3: 