In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets  import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection  import train_test_split

In [22]:
x,y=make_classification(
    n_features=10,
    n_samples=1000,
    n_informative=4,
    n_redundant=6,
    n_repeated=0,
    n_classes=2,
    weights=[0.9,0.1],
    random_state=42
)

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.25,random_state=42)

In [3]:
model=LogisticRegression()
model.fit(x_train,y_train)
from sklearn.metrics import classification_report

y_pred=model.predict(x_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.66      0.69      0.67       122
           1       0.69      0.66      0.68       128

    accuracy                           0.68       250
   macro avg       0.68      0.68      0.68       250
weighted avg       0.68      0.68      0.68       250



# K Fold

In [ ]:
from sklearn.model_selection import KFold

kf=KFold(n_splits=5,shuffle=True,random_state=42)

score1=[]
for train_index,test_index in kf.split(x,y):
    x_train,x_test=x[train_index],x[test_index]
    y_train,y_test=y[train_index],y[test_index]

    model.fit(x_train,y_train)
    score1.append(model.score(x_test,y_test))

In [ ]:
np.mean(score1)

np.float64(0.704)

# Cross Validation Score

## Evaluating Logistic Regression model

In [12]:
from sklearn.model_selection import cross_val_score

scores=cross_val_score(LogisticRegression(),x,y,cv=kf)
scores

array([0.705, 0.63 , 0.73 , 0.765, 0.69 ])

In [13]:
np.mean(scores)

np.float64(0.704)

## Evaluating Decision tree model

In [14]:
from sklearn.tree import DecisionTreeClassifier

decision_tree_score=cross_val_score(DecisionTreeClassifier(),x,y,cv=kf)
decision_tree_score

array([0.895, 0.855, 0.915, 0.905, 0.85 ])

In [15]:
np.mean(decision_tree_score)

np.float64(0.884)

## Evaluating XGboost

In [18]:
from xgboost import XGBClassifier

xgboost_score=cross_val_score(XGBClassifier(),x,y,cv=5)
xgboost_score

array([0.895, 0.91 , 0.92 , 0.93 , 0.95 ])

In [19]:
np.mean(xgboost_score)

np.float64(0.921)

# Cross validation

In [20]:
from sklearn.model_selection import cross_validate

cross_validate(DecisionTreeClassifier(),x,y,cv=kf,scoring=['accuracy','roc_auc'])

{'fit_time': array([0.00440359, 0.00427294, 0.00407505, 0.00380254, 0.00395417]),
 'score_time': array([0.00614214, 0.00237989, 0.00191665, 0.00209451, 0.00230193]),
 'test_accuracy': array([0.895, 0.875, 0.9  , 0.915, 0.875]),
 'test_roc_auc': array([0.89583333, 0.87665596, 0.89988999, 0.91684468, 0.87293233])}

# stratified K fold cross validation

In [25]:
from collections import Counter

Counter(y)# true=90% ,flase=10%

Counter({np.int64(0): 892, np.int64(1): 108})

In [26]:
from sklearn.model_selection import StratifiedKFold

skf=StratifiedKFold(n_splits=5,shuffle=True,random_state=42)

for train_index,test_index in skf.split(x,y):
    x_train,x_test=x[train_index],x[test_index]
    y_train,y_test=y[train_index],y[test_index]
    print(Counter(y_test))

Counter({np.int64(0): 179, np.int64(1): 21})
Counter({np.int64(0): 179, np.int64(1): 21})
Counter({np.int64(0): 178, np.int64(1): 22})
Counter({np.int64(0): 178, np.int64(1): 22})
Counter({np.int64(0): 178, np.int64(1): 22})


## Evaluationg models using skf

## decision tree classifier

In [27]:
cross_val_score(DecisionTreeClassifier(),x,y,cv=skf,scoring='accuracy')

array([0.915, 0.945, 0.945, 0.945, 0.92 ])

### XGBoost classifier

In [28]:
cross_val_score(XGBClassifier(),x,y,cv=skf)

array([0.95 , 0.955, 0.95 , 0.95 , 0.925])